// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spyoaniarzarsmwyrani.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNweW9hbmlhcnphcnNtd3lyYW5pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDAxMjMsImV4cCI6MjA3NDY3NjEyM30.Q3bvutNBgYrucSfNJO8NnCsaQ-idjVzOF74iDYwXPEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});